package enums;

public enum enumDirecao {
    HORIZONTAL_DIREITA,
    HORIZONTAL_ESQUERDA,
    VERTICAL_CIMA,
    VERTICAL_BAIXO,
    DIAGONAL_CIMA_ESQUERDA,
    DIAGONAL_CIMA_DIREITA,
    DIAGONAL_BAIXO_ESQUERDA,
    DIAGONAL_BAIXO_DIREITA
}
